name: CI Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 3 * * *' # daily, at 3am
env:
  CI: true

jobs:
  test:
    name: Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
        with:
          node-version: 10.x
      - run: yarn install --frozen-lockfile
      - run: yarn test

  floating-dependencies:
    name: "Floating Dependencies"
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
        with:
          node-version: 10.x
      - run: yarn install --no-lockfile
      - run: yarn test

  try-scenarios:
    name: "Try: ${{ matrix.ember-try-scenario }}"
    timeout-minutes: 60

    runs-on: ubuntu-latest

    needs: test

    strategy:
      fail-fast: true
      matrix:
        ember-try-scenario:
          - ember-lts-3.16
          - ember-lts-3.20
          - ember-release
          - ember-beta
          - ember-canary
          - ember-classic
          - ember-default-with-jquery

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
        with:
          node-version: 12.x
      - name: install dependencies
        run: yarn install --frozen-lockfile
      - name: test
        run: node_modules/.bin/ember try:one ${{ matrix.ember-try-scenario }} --skip-cleanup
